[package]
name = "session"
version = "0.0.0"
publish = false

[workspace]

[dependencies]
rocket = { path = "../../core/lib", features = ["private-cookies"] }
ring = "0.13"

[dependencies.rocket_contrib]
path = "../../contrib/lib"
default-features = false
features = ["handlebars_templates"]
